// Technical Program Committee
var tcps_arrays =[
"Claude Delpha (University Paris-SuD XI, France)",
"Jana Dittmann (University Magdeburg, Germany)",
"Patrick Bas (École Centrale de Lille - CNRS, France)",
"Isao Echizen (National Institute of Informatics, Japan)",
"Xinghao Jiang (Shanghai Jiao Tong University, China)",
"Tomáš Pevný (Czech Technical University in Prague, Czech)",
"Xiangui Kang (Sun Yat-sen University, China)",
"Mohan Kankanhalli (National University of Singapore, Singapore)",
"Minoru Kuribayashi (Okayama University, Japan)",
"Xiaolong Li (Beijing Jiaotong University, China)",
"Chang-Tsun Li (Charles Sturt University, Australia)",
"Feng Liu (CAS, China)",
"Rémi Cogranne (Troyes University of Technology, France)",
"Xiangyang Luo (Information Engineering University, China)",
"Yi Hu (Northern Kentucky University, USA)",
"Fangjun Huang (Sun Yat-sen University, China)",
"Jessica Fridrich (Binghamton University, USA)",
"Bin Ma (Qilu University of Technology, China)",
"Wojciech Mazurczyk (Warsaw University of Technology, Poland)",
"Rongrong Ni (Beijing Jiaotong University, China)",
"Chin-Chen Chang (Feng Chia University, Taiwan)",
"Jiangqun Ni (Sun Yat-sen University, China)",
"Akira Nishimura (Tokyo University of Information Sciences, Japan)",
"Xingming Sun (Nanjing University of Information Science & Technology, China)",
"Xianfeng Zhao (CAS, China)",
"Yong-Man Ro (KAIST, Korea)",
"Hongxia Wang (Sichuan University, China)",
"James C. N. Yang (National Dong Hwa University, Taiwan)",
"Linna Zhou (University of International Relations, China)",
"Athanassios Skodras (University of Patras, Greece)",
"Xinpeng Zhang (Fudan University, China)",
"Stefan Katzenbeisser (TU Darmstadt, Germany)",
"Weiming Zhang (University of Science and Technology of China, China)",
"Guopu Zhu (CAS, China)",
"Yao Zhao (Beijing Jiaotong University, China)",
"Cheonshik Kim (Sejong University, Korea)",
"Matthew Stamm (Drexel University, USA)",
"Andreas Westfeld (HTW Dresden, Germany)",
"Anja Keskinarkaus (University of Oulu, Finland)",
"Andrew Ker (University of Oxford, UK)"
];

// List of Accepted Papers
var accepted_papers=[
    "*****************************",
    "*****************************",
    "*****************************",
    "*****************************",
];